on:
  push:
    branches: main
jobs:
  import-data:
    runs-on: ubuntu-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::tidyverse 
            any::ggplot2
            any::dplyr
            any::tidyverse
            any::data.table
            any::MASS
            any::wooldridge
            any::stargazer
            any::stringdist
            any::sf
            any::readxl
            any::lmtest
            any::reshape2
            any::rvest
            any::stringr
            any::httr
            any::writexl
            any::purrr
            any::jsonlite
            any::tidycensus
            any::googleway
            any::tidygeocoder

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Import data
        run: Rscript -e 'source("Predict DMV Data 2 Aug.R")'

      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add survey_data.rds
          git commit -m 'Data updated' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
